---
version: 2
project_name: terrascaler
builds:
  - id: terrascaler
    main: ./cmd/terrascaler
    binary: terrascaler
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
dockers_v2:
  - images:
      - ghcr.io/containeroo/terrascaler
      - containeroo/terrascaler
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: Dockerfile.goreleaser
    ids:
      - terrascaler
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - --pull
      - --cache-from=type=gha,scope=terrascaler
      - --cache-to=type=gha,mode=max,scope=terrascaler
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: External gRPC cloud provider for Kubernetes Cluster Autoscaler backed by GitLab and Terraform/OpenTofu
      org.opencontainers.image.url: https://github.com/containeroo/terrascaler
      org.opencontainers.image.source: https://github.com/containeroo/terrascaler
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: '{{ time "2006-01-02T15:04:05Z07:00" }}'
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: GNU General Public License v3.0
release:
  prerelease: auto
